<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cotizador</title>
    <link rel="stylesheet" href="./style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@900&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        footer{
  
        height: 41vw;
        position: absolute;
        top: 0vw!important;
        
        }
    </style>
</head>
<body>


<div class="header">  
  <img src="./img/logo.png" width="6%" style="margin-top: 2.5vw;margin-left:4vw">
  <p style="position:absolute; top:0vw; right:5vw"><a href="#contacto" style="color:#ccc">Contáctenos</a> <a href="#blog" style="color:#ccc">Blog</a> 
  <a href="#whatsapp" style="color:white"><img src="./img/Whatsapp.svg" width="8%" style="margin-top: 2.5vw;margin-left:0.5vw"></a>
  <a href="#email" style="color:white"><img src="./img/Email_Header.svg" width="8%" style="margin-top: 2.5vw;margin-left:0.5vw"></a>
  <span class="number">(55)-8978-1800</span>
</p>
</div>
	
    <section class="seccion">

   

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="./img/bannerprincipal.jpeg" usemap="#image-map">

<a href="planes-retiro.php">
<div class="img1"></div>
</a>
<a href="family.php">
<div class="img2"></div>
</a>
<a href="vehicle.php">
<div class="img3"></div>
</a>
<a href="hogar.php">
<div class="img4"></div>
</a>
<a href="planes.php">
<div class="img5"></div>
</a>

<!-- Image Map Generated by http://www.image-map.net/ 
<img src="seguro.png" usemap="#image-map">

<map name="image-map">
    <area target="_self" alt="House" title="House" href="house.html" coords="37,360,487,11" shape="rect">
    <area target="_self" alt="Planes de ahorro" title="Planes de ahorro" href="planes-retiro.php" coords="36,396,483,732" shape="rect">
    <area target="_self" alt="medico" title="medico" href="medico.html" coords="504,216,891,522" shape="rect">
    <area target="_self" alt="vehicle" title="vehicle" href="vehicle.html" coords="907,16,1341,303" shape="rect">
    <area target="_self" alt="planes" title="planes" href="planes.html" coords="918,436,1340,746" shape="rect">
</map>
-->
    </section>
    <div class='pre-loader'>
    <img class='loading-gif' alt='loading' src="https://media0.giphy.com/media/11FuEnXyGsXFba/source.gif"/>
</div>

<!-- js to hide preloader loading is done -->
<script type='text/javascript'>
    window.addEventListener('load', function () {
        document.querySelector('.pre-loader').className += ' hidden';
    });
</script>
<section class="mapa">
    <div class="mapagif">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15666.900076368749!2d-64.036348369909!3d10.984116191585708!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c31f39452f99be7%3A0x1c070edc6b6df8a7!2sPiedras%20Negras%2C%20Nueva%20Esparta!5e0!3m2!1ses!2sve!4v1695845805479!5m2!1ses!2sve" width="500" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    <div class="rutagif">
    <span class="title1"> Seguros y Fianzas</span><br>
    <span class="title2">Agente de Seguros</span><br>
<br>
<span class="title1">Nuestra dirección</span><br>
<span class="title2">Ejército Republicano 121,</span><br>
<span class="title2">Carretas, 76050 Santiago de Querétaro, Qro.</span><br>
<img class="icn_whatsapp" src="img/icn-whatsapp.png">
<span class="title2">(55) 8978-1800</span>
   

</div>
</section>
<link rel="stylesheet" href="./style.css">
<footer>
 
<div class="footerpie">  
<div class="row">
<div class="columna5">
<h5><strong>Seguro de Autos</strong></h5><br>
<h6>Seguro de Auto ABA Auto Seguro</h6>
<h6>Seguro de Auto ANA Seguros</h6>
<h6>Seguro de Auto HDI Seguros</h6>
<h6>Seguro de Auto Qualitas</h6>
<h6>Seguro de Auto Sura</h6>
</div>
<div class="columna6">
<h5><strong>Seguros Gastos Médicos Mayores</strong></h5><br>
<h6>Seguro de Gastos Médicos Mayores Atlas Seguros</h6>
<h6>Seguro de Gastos Médicos Mayores AXA Seguros</h6>
<h6>Seguro de Gastos Médicos Mayores Seguros Ve por Más</h6>
<h6>Seguro de Gastos Médicos Mayores Seguros GNP</h6>
</div>


</div>


</div>
<div class="row">
<div class="pie">
Consulta nuestro Aviso de Privacidad y Términos de Uso
</div>
</div>
</footer>




</body>
</html>